sudo: required
dist: trusty
language: node_js
node_js:
  - '6'

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
- npm install -g angular-cli
- npm install -g karma
- npm install -g npm@4.1.2
- npm install
- ng build

script: karma start karma.conf.js --single-run

deploy:
  provider: heroku
  app: sc68
  on:
    repo: p-engelkes/sc68_frontend
    branch: travis-ci
  api_key: 2e82ac0c-5af0-41d6-baa7-dcd16e298fea
